create table User(
ID varchar(100),
USERNAME VARCHAR(100),
PASSWORD VARCHAR(100),
/*PASSWORD_EXPIRED VARCHAR(100),*/
ROLE_ID VARCHAR(100),
CREATE_TIME TIMESTAMP DEFAULT CURRENT TIME,
EMPLOYEE_ID VARCHAR (100)
);